version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greenindia
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
